#!/bin/sh

echo "# autogenerated addons $(uname -r)" > pcitable-kanotix.auto

awk '/r8180|sk98lin|snd-|tg3/ {print $2"\t"$3"\t\""$1"\""}' /lib/modules/$(uname -r)/modules.pcimap | \
	sed s/0000//g | \
	grep -v -E 'snd-bt87x|snd-intel8x0m|snd-via82xx-modem|snd-atiixp-modem' \
	>> pcitable-kanotix.auto
