#!/bin/sh
echo '# autogenerated addons' > pcitable-kanotix.auto
awk '/r8180|sk98lin|snd-|tg3/ {print $2"\t"$3"\t\""$1"\""}' /lib/modules/$(uname -r)/modules.pcimap |sed s/0000//g >> pcitable-kanotix.auto
